# Generated by Django 5.1 on 2024-08-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity_sold', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('review_count', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
